version: "3.8"

services:
  app:
    image: quran-app-dev
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes: 
      - ./public:/app/public
      - ./src/app/assets:/app/src/app/assets
